### ISSUE TITLE
Not authenticate in Instagram

### ISSUE THREAD

**Issue by gesielbernardes** [CamTosh/instagram-bot-dm#11]
Hi, I'm testing code below, but browser open and noting happen.

`from instadm import InstaDM

if __name__ == '__main__':
	# Auto login
	insta = InstaDM(username='my_user', password='my_password', headless=False)
	
	# Send message
	insta.sendMessage(user='my_user_test', message='Teste!')`

This error showing in the console:
\$ python3 dm.py
ERROR:root:Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="username"]"}
  (Session info: chrome=85.0.4183.121)

ERROR:root:'NoneType' object has no attribute 'send_keys'
Exception when __typeSlow__ : 'NoneType' object has no attribute 'send_keys'

Using:
Ubuntu 20.04
  chromium-chromedriver                         1:85.0.4183.83-0ubuntu0.20.04.1
Python 3.8.2
  selenium 3.141.0

**Comment by hbollon** [comment]
Same here with the following script : 
`
from instadm import InstaDM
from instapy import InstaPy
from time import sleep
import random
import csv

templateDm = "some random stuff"
srcUser = "****"

def extractUsers():
    csv_file = 'extracted_users.csv'
    usernames = []

    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            usernames.append(row.get('Username'))
    return usernames


if __name__ == '__main__':
    # Recover follower list from srcUser account
    followers = extractUsers()

    # Auto login
    insta = InstaDM(username='****',
                    password='****', headless=True)

    # Send message
    for user in followers:
        insta.sendMessage(user=user, message=templateDm)
        print("Dm sent to "+user)
        sleep(random.randint(45, 60))
`

Using:
Ubuntu 18.04
ChromeDriver 85.0.4183.121
Python 3.6.9
Selenium 3.141.0

**Comment by CamTosh** [comment]
Can you check  @kowshika-n ? :)

**Comment by kowshika-n** [comment]
I don't have access to an Ubuntu system but I guess the issue could be due to language difference. 
Can you try checking with URL with language parameter like `self.driver.get('http://instagram.com/?hl=en')`

**Comment by hbollon** [comment]
Okay it's works ! 
I had to add ``` /?hl=en ``` on the three ``` self.driver.get ``` calls.
With these changes, it seems to works perfectly! :)
Thanks!

**Comment by kowshika-n** [comment]
This will be minor change. Thanks for the confirmation.

**Comment by kowshika-n** [comment]
@CamTosh This issue can be resolved by Merge #13

**Comment by CamTosh** [comment]
Thanks !
