### ISSUE TITLE
Can't send multi line messages 

### ISSUE THREAD

**Issue by appelmoesje** [CamTosh/instagram-bot-dm#28]
When sending a multi line message with the sendMessage or the sendGroupMessage method the "Send" button disappears. When the message is fully typed the bot tries to send it by looking for the "Send" button but it can't be found. 

I tried to solve this by pressing the Keys.RETRUN or Keys.ENTER buttons, but both don't work.

EDIT:
Found out that it can't press the "Send" button because the "This web browser is no longer supported." banner is in the way. I don't know how to upgrade the browser without breaking the bot.

My solutuon is to remove the banner with the following code in the typeMessage method just before the click on the send button.
```
try:
     element = self.driver.find_element_by_class_name('pwPDf')
     self.driver.execute_script("""
     var element = arguments[0];
     element.parentNode.removeChild(element);
     """, element)
except:
    pass
```

**Comment by tygovanhalm** [comment]
Hey appelmoesje, is er een manier waarop ik je kan bereiken? Groet, Tygo.

**Comment by M4rkoHR** [comment]
change the user agent (line 44)
