### ISSUE TITLE
can I use this for a Telegram style bot?

### ISSUE THREAD

**Issue by hadifarnoud** [CamTosh/instagram-bot-dm#4]
I want to automate customer orders via a chat bot. can I use this for that? below is a example how it works:

(c) means customer and (b) is bot replying
(c) sends a DM
(b) how are you today? for placing an order send 1 and for talking to a person send 5
(c) 1
(b) please send product code. you can find product code below any post in caption
(c) E873
(b) this product is $87. if you want to order it, please let me know how many. if not, please reply with NO
(c) 1
....

you get the idea. this would be super cool. I can even think of Customer Support scenarios

**Comment by hadifarnoud** [comment]
Why was this issue closed? Would you please let me know if this is possible with instagram-bot-dm?

**Comment by CamTosh** [comment]
Hello, of course instagram-bot-dm allows you to send private messages on instagram. I haven't tried it for a long time, I don't know if it still works.
