### ISSUE TITLE
⚡ Thank you a lot for this amazing work ! 

### ISSUE THREAD

**Issue by ErrorxCode** [CamTosh/instagram-bot-dm#49]
Hey thank you for this amazing lib !

**Comment by CamTosh** [comment]
🫶

**Comment by ErrorxCode** [comment]
Cool !

![image](https://user-images.githubusercontent.com/65817230/230746688-6b9fd955-72e5-466c-8348-f1841b859222.png)

How gonna you hide this now ?

**Comment by CamTosh** [comment]
It's funny 🤡

**Comment by ErrorxCode** [comment]
You will be going to spoil your issues for this fun :)
